### ISSUE TITLE
Create an issue with -issue-create and provide a description

### ISSUE THREAD

**Issue by voigt** [toabctl/jiracli#16]
```
jiracli [-h] [--debug] [--issue-type-list] [--issue-link-types-list]
               [--project-list] [--project-list-components project-key]
               [-m message] [--filter-list-fav] [--no-color]
               [-c project-key issue-type summary labels components]
```
According to `jiracli -h` its not possible to provide an issue description when creating an issue. Will this feature be supported any time?
Is it possible to edit the description of an existing issue?

Kind Regards,
Christoph

**Comment by toabctl** [comment]
@voigt well - create a pull request with a patch to support the features you want :-) At least adding the description while creating an issue shouldn't be to hard...

**Comment by toabctl** [comment]
@voigt I recognized that you can already add a description when you create a new issue. `jiracli` opens your prefered editor to insert the description. Just try it with i.e. 

```jiracli --issue-create myproject mytype mysubject "" ""```

**Comment by toabctl** [comment]
So this one is already working. Closing....
