### ISSUE TITLE
terminal height and width reversed on sprint output

### ISSUE THREAD

**Issue by dam5h** [toabctl/jiracli#18]
To get the correct output on 
```
jiracli --sprint 
```
The problem was that the summary column was always truncated.

I needed to reverse the tuple unpacking.  sttysize gives rows, columns rather than columns, rows.

Making this change in line 81 of __init__.py solved my issue.

**Comment by toabctl** [comment]
Do you want to send a pull request?

**Comment by dam5h** [comment]
Sure

**Comment by toabctl** [comment]
Closed via https://github.com/toabctl/jiracli/pull/19
