### ISSUE TITLE
Transition to custom state

### ISSUE THREAD

**Issue by yosh-se** [toabctl/jiracli#29]
Right now, it's possible to transition to start, resolved and closed. I'd like another function that took the next transition state as an parameter since I have a larger workflow with more states.

**Comment by torrancew** [comment]
I believe this would potentially be solved by #8

**Comment by yosh-se** [comment]
Sorry, didn't see that one. Yes it's a dupe to this.

**Comment by blatinier** [comment]
It wasn't so much a duplicate since this is an issue and #8 is a PR. I updated the PR to be ready for merge. In the meanwhile you can clone from my repo (http://github.com/blatinier/jiracli).
