### ISSUE TITLE
Query Issue Status

### ISSUE THREAD

**Issue by KBPratap** [toabctl/jiracli#43]
Is there a way to query the current-status of an issue?
Something 
like - **`jiracli -i PROJECT-123 --issue-status`**
similar to - **`jiracli -i PROJECT-123 --issue-comments`**

**Comment by toabctl** [comment]
@KBPratap The status is listed in the headline whn showing an issue:
```
$ jiracli  -i DOCUMENT-627
DOCUMENT-627, Improvement: Hiera / Puppet version compatibility (Resolved, Normal)
created              : Fri Dec 16 04:03:30 2016, by renflo
assignee             : jean
updated              : Wed Dec 21 17:02:45 2016
components           : Hiera, Puppet Language, Puppet Server
comments             : 1
```

**Comment by toabctl** [comment]
Answered with https://github.com/toabctl/jiracli/issues/43#issuecomment-268976083 . Please reopen if this doesn't solve your problem.

**Comment by toabctl** [comment]
Answered with https://github.com/toabctl/jiracli/issues/43#issuecomment-268976083 . Please reopen if this doesn't solve your problem.
