### ISSUE TITLE
Moving core logic

### ISSUE THREAD

**Issue by tusharmakkar08** [toabctl/jiracli#45]
Hey @toabctl 

I was thinking to move core logic from `__init__.py` to maybe `jira_cli.py`. I personally feel keeping the core logic code in `__init__.py` isn't a great thing. I can create a PR with modified structure. 

Let me know what you think about it. 

Regards
Tushar Makkar

**Comment by toabctl** [comment]
@tusharmakkar08 Hi. Hm. I currently don't see a big benefit of doing this. If the project grows, we could reconsider a move but currently I'm against it.
