### ISSUE TITLE
How to query all issues in a sprint over many projects

### ISSUE THREAD

**Issue by robotex82** [toabctl/jiracli#46]
First of all, jiracli is awesome!

But there is a small thing missing for me to be really useful. How can I query all issues that are in the actual sprint, that contains issues from many different projects?

Something like

    jiracli --sprint *

Thanks in advance!

Best regards
Roberto

**Comment by toabctl** [comment]
You can search directly with jql (see https://github.com/toabctl/jiracli#example-searching-with-jql ) or create a filter in the UI and use it with jiraclie (see https://github.com/toabctl/jiracli#example-use-favourite-filters ). Does that help?

**Comment by robotex82** [comment]
For future reference:

Works like a charm:

    jiracli --issue-search "assignee = currentUser() AND sprint in openSprints() AND sprint not in futureSprints()"
